# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='image_list',
            field=models.ManyToManyField(to='api.CollectionImage'),
        ),
    ]
