# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170913_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
