# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='press/')),
                ('contents', models.TextField(max_length=1000)),
                ('order', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
