# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170919_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('Collection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Collection')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
