# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171012_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='qiniu_gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='Collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='qiniu_images', to='api.Collection'),
        ),
    ]
