# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171012_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
