# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171012_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='qiniu_gallery',
        ),
    ]
