# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_collection_qiniu_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
