# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_collection_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Collection',
            new_name='collection',
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
