# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171022_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='gallery',
        ),
        migrations.AddField(
            model_name='image',
            name='image_qiniu',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
