# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171023_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_qiniu',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
