# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 09:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171023_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='stock_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='api.StockList'),
        ),
    ]
