# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171023_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='stock_list',
        ),
        migrations.AddField(
            model_name='stocklist',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='api.Country'),
        ),
    ]
