# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171023_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name_plural': 'presses'},
        ),
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
