# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171023_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_stock_list', models.BooleanField(default=False)),
                ('show_language_menu', models.BooleanField(default=False)),
            ],
        ),
    ]
