# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171024_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
        ),
    ]
