# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 14:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20171024_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contents_cn',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='name_cn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='contents_cn',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='press',
            name='contents_cn',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='press',
            name='title_cn',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='address_cn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='city_cn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='phone_cn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='store_name_cn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='contents',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='contents',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='press',
            name='contents',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='press',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
