# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171024_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to=''),
        ),
    ]
