# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20171024_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cover_image',
            field=models.ImageField(default='', max_length=200, upload_to=''),
        ),
    ]
