# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_settings_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.TextField(default='Home', max_length=100)),
                ('home_cn', models.TextField(default='Home', max_length=100)),
                ('collection', models.TextField(default='Collection', max_length=100)),
                ('collection_cn', models.TextField(default='Collection', max_length=100)),
                ('campaign', models.TextField(default='Campaign', max_length=100)),
                ('campaign_cn', models.TextField(default='Campaign', max_length=100)),
                ('stock_list', models.TextField(default='Stock list', max_length=100)),
                ('stock_list_cn', models.TextField(default='Stock list', max_length=100)),
                ('press', models.TextField(default='Press', max_length=100)),
                ('press_cn', models.TextField(default='Press', max_length=100)),
                ('about', models.TextField(default='About', max_length=100)),
                ('about_cn', models.TextField(default='About', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'menu',
            },
        ),
    ]
