# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20171111_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='about',
            field=models.CharField(default='About', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='about_cn',
            field=models.CharField(default='About', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='campaign',
            field=models.CharField(default='Campaign', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='campaign_cn',
            field=models.CharField(default='Campaign', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='collection',
            field=models.CharField(default='Collection', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='collection_cn',
            field=models.CharField(default='Collection', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='home',
            field=models.CharField(default='Home', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='home_cn',
            field=models.CharField(default='Home', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='press',
            field=models.CharField(default='Press', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='press_cn',
            field=models.CharField(default='Press', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='stock_list',
            field=models.CharField(default='Stock list', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='stock_list_cn',
            field=models.CharField(default='Stock list', max_length=10),
        ),
        migrations.AlterField(
            model_name='press',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='press',
            name='title_cn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_first_line',
            field=models.CharField(default='', max_length=33),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_second_line',
            field=models.CharField(default='', max_length=33),
        ),
    ]
